### ISSUE TITLE
Changing the admin PW via UI does not survive the restart of the container

### ISSUE THREAD

**Issue by dakky** [openshift/jenkins#134]
Hello

I'm using openshift/jenkins-1-rhel7.
After changing the admin pw via the UI i can login with the new password. . But after restarting the container, the password configured in the environment ist set again.

In fact, the following code does not work:
https://github.com/openshift/jenkins/blob/master/1/contrib/s2i/run

[...]
 90:  if [ $old_password!=$new_password_hash ]; then
[...]

the password hash ALWAYS differs, even if the password is the same => the password is always reset to the one configured in the env.

**Comment by gabemontero** [comment]
You most likely are using the ephemeral template.  To have configuration
persist across constainer restarts you need to use the persistent template
and define an associated PV.

**Comment by dakky** [comment]
Hello :)

Nope i'm using the persistent template:

```
apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  labels:
    app: jenkins
    template: jenkins-master-s2i
  name: jenkins
spec:
  replicas: 1
  selector:
    app: jenkins
    deploymentconfig: jenkins
  strategy:
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: jenkins
        deploymentconfig: jenkins
    spec:
      containers:
      - env:
        - name: JENKINS_PASSWORD
          value: password
        image: jenkins
        imagePullPolicy: Always
        name: jenkins
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 50000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /var/lib/jenkins
          name: jenkins-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: jenkins-data
        persistentVolumeClaim:
          claimName: jenkins
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - jenkins
      from:
        kind: ImageStreamTag
        name: jenkins:latest
    type: ImageChange
```

I also logged in the containers and compared the strings in the password file: they differ.
