### ISSUE TITLE
s2i customization makes image unstartable

### ISSUE THREAD

**Issue by dakky** [openshift/jenkins#135]
Hello

i'm trying to customize the jenkins image openshift/jenkins-1-rhel7. The original image seems to work fine.

As "base" is use: https://github.com/siamaksade/jenkins-s2i-example

In order to customize the image, i have the following buildconfig:

```
[...]
			"source": {
				"contextDir": "jenkins-s2i/s2i/master",
				"git": {
					"uri": "https://git.repo.intern/scm/team/openshift.git",
					"ref": "develop"
				},
				"sourceSecret": {
					"name": "builder"
				},
				"type": "Git"
			},
			"strategy": {
				"sourceStrategy": {
					"from": {
						"kind": "ImageStreamTag",
						"name": "jenkins-1-rhel7:latest",
						"namespace": "openshift"
					}
				},
				"type": "Source"
[...]
```

The build itself works fine (here only the source part): 

```
[...]
I0809 05:35:07.885356       1 docker.go:622] Attaching to container "74ac9f156f6837cfb60aef16974367e4f88a5f84bf50030d6f67caf190c85068" ...
I0809 05:35:07.885832       1 docker.go:631] Starting container "74ac9f156f6837cfb60aef16974367e4f88a5f84bf50030d6f67caf190c85068" ...
---> Copying repository files ...
---> Installing Jenkins 4 plugins using /opt/openshift/plugins.txt ...
Downloading git-2.4.4 ...
Downloading scm-api-1.0 ...
Downloading git-client-1.19.6 ...
Downloading greenballs-1.15 ...
---> Removing sample Jenkins job ...
---> Installing new Jenkins configuration ...
I0809 05:35:13.792601       1 docker.go:689] Invoking postExecution function
I0809 05:35:13.792678       1 sti.go:289] No user environment provided (no environment file found in application sources)
E0809 05:35:13.792828       1 sti.go:571] Error reading docker stdout, EOF
I0809 05:35:13.838642       1 docker.go:734] Committing container with dockerOpts: {Container:74ac9f156f ....
[...]
```

But when starting the built image i get the following error:

```
touch: cannot touch ‘/var/jenkins_home/copy_reference_file.log’: Permission denied
Can not write to /var/jenkins_home/copy_reference_file.log. Wrong volume permissions?
```

it SEEMS to be the original /usr/local/bin/jenkins startupfile and not the customized one? Just a guess.

Any idea?

**Comment by bparees** [comment]
I can't access your repo, are you overriding the run script in your repository?  

Also the image we produce expects to write to /var/lib/jenkins, not var/jenkins_home, other directories won't have the correct permissions, so if you're changing that, you need to change permissions on the directories.

**Comment by dakky** [comment]
Hello ;)

No, I don't override the run script. Have a look here: https://github.com/siamaksade/jenkins-s2i-example

Thats what I am using basically. 
I changed the directory layout in order to fit in to our company setup (and of course fixed the contextDir in the buildconfig) but i did not change any of the jenkins specific setup files. Only the openshift part was modified: layout directory, cleaned up some unnessecary env variables but thats it. sry i can't give you access to die repo, but its under NDA :(

Here is the structure:
```
.
├── bc
│   └── jenkins-master-s2i-buildconfig.json
├── is
│   └── jenkins-master-s2i-imagestream.json
├── s2i
│   ├── master
│   │   ├── configuration
│   │   │   ├── config.xml.tpl
│   │   │   ├── hudson.tasks.Maven.xml
│   │   │   ├── jobs
│   │   │   │   └── tasks-build
│   │   │   │       └── config.xml
│   │   │   ├── nexus-settings.xml
│   │   │   └── settings.xml
│   │   └── plugins.txt
│   └── slave
│       ├── configuration
│       │   ├── nexus-settings.xml
│       │   ├── passwd.template
│       │   ├── run-jnlp-client
│       │   └── settings.xml
│       └── Dockerfile
└── template
    └── jenkins-master-s2i-template.json
```

**Comment by bparees** [comment]
are you changing the JENKINS_HOME env variable?

**Comment by dakky** [comment]
not explicitly.

```
oc  env dc jenkins --list
# deploymentconfigs jenkins, container jenkins
JENKINS_PASSWORD=password
```

**Comment by bparees** [comment]
i mean in the image you are building.

**Comment by dakky** [comment]
nope (I think ;) )
i did not add any s2i scripts in order to overwrite the orignal ones, so this should be ok. 
The only env I added in the buildconfig is a http/https proxy

**Comment by bparees** [comment]
can i see your deployment config and all of your buildconfig?

**Comment by bparees** [comment]
also your buildconfig setting "contextDir": "jenkins-s2i/s2i/master", yet the repo structure you showed me doesn't have a "jenkins-s2i" root directory?

**Comment by dakky** [comment]
of course, here you are:
Deploymentconfig:
```
apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  labels:
    app: jenkins
    template: jenkins-master-s2i
  name: jenkins
spec:
  replicas: 1
  selector:
    app: jenkins
    deploymentconfig: jenkins
  strategy:
    recreateParams: {}
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: jenkins
        deploymentconfig: jenkins
    spec:
      containers:
      - env:
        - name: JENKINS_PASSWORD
          value: password
        image: jenkins
        imagePullPolicy: Always
        name: jenkins
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 50000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /var/lib/jenkins
          name: jenkins-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: jenkins-data
        persistentVolumeClaim:
          claimName: jenkins
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - jenkins
      from:
        kind: ImageStreamTag
        name: jenkins:latest
    type: ImageChange
status: {}
```

buildconfig:
```
apiVersion: v1
kind: BuildConfig
metadata:
  creationTimestamp: null
  labels:
    app: jenkins
  name: jenkins
spec:
  output:
    to:
      kind: ImageStreamTag
      name: jenkins:latest
  resources:
    limits:
      memory: 512M
  source:
    contextDir: jenkins-s2i/openshift/s2i/master
    git:
      ref: develop
      uri: https://git.repo.intern/scm/team/openshift-base.git
    sourceSecret:
      name: builder
    type: Git
  strategy:
    sourceStrategy:
      env:
      - name: https_proxy
        value: proxy:3128
      - name: http_proxy
        value: proxy:3128
      from:
        kind: ImageStreamTag
        name: jenkins-1-rhel7:latest
        namespace: openshift
    type: Source
  triggers:
  - type: ConfigChange
  - imageChange: {}
    type: ImageChange
status:
  lastVersion: 0
```

the "jenkins-s2i" folder is the "." in the most upper hierarchy. Here a snipplet from the project root:
```
.
+--- .git
+--- .gitignore
+--- bin
+--- docs
+--- some_module
+--- some_module
+--- jenkins-s2i
|   +--- openshift
|   |   +--- bc
|   |   |   +--- jenkins-master-s2i-buildconfig.json
|   |   +--- is
|   |   |   +--- jenkins-master-s2i-imagestream.json
|   |   +--- jenkins-master-s2i-template.yaml
|   |   +--- jenkins-slave-builder-template.yaml
|   |   +--- s2i
|   |   |   +--- master
|   |   |   |   +--- configuration
|   |   |   |   |   +--- config.xml.tpl
|   |   |   |   |   +--- hudson.tasks.Maven.xml
|   |   |   |   |   +--- jobs
|   |   |   |   |   |   +--- tasks-build
|   |   |   |   |   |   |   +--- config.xml
|   |   |   |   |   +--- nexus-settings.xml
|   |   |   |   |   +--- settings.xml
|   |   |   |   +--- plugins.txt
|   |   |   +--- slave
|   |   |   |   +--- configuration
|   |   |   |   |   +--- nexus-settings.xml
|   |   |   |   |   +--- passwd.template
|   |   |   |   |   +--- run-jnlp-client
|   |   |   |   |   +--- settings.xml
|   |   |   |   +--- Dockerfile
|   |   +--- template
|   |   |   +--- jenkins-master-s2i-template.json
|   +--- README.md
+--- some_module
+--- some_module
+--- some_module
```
