### ISSUE TITLE
Cannot modify cloud settings using JCasC

### ISSUE THREAD

**Issue by jlebon** [openshift/jenkins#1505]
In the Fedora CoreOS pipeline, we wanted to edit some settings of the `openshift` cloud to try to work around some issues (https://github.com/coreos/fedora-coreos-pipeline/pull/580). Unfortunately, we had to revert it (https://github.com/coreos/fedora-coreos-pipeline/pull/583) because it would overwrite the cloud config generated by the S2I run script.

What's the recommended approach to tweaking cloud knobs?

**Comment by jlebon** [comment]
We ended up working around this by defining the `openshift` cloud ourselves using the following JCasC dropin:

```yaml
jenkins:
  clouds:
  - kubernetes:
      # The keys below match
      # https://github.com/openshift/jenkins/blob/7bae76f4412d/2/contrib/jenkins/kube-slave-common.sh#L75
      # except that we don't include the templates since we don't need them.
      # We also don't include the certificate; it's automatically fetched from
      # the serviceaccount, which is what the the s2i run script does anyway.
      name: "openshift"
      addMasterProxyEnvVars: true
      containerCap: 100
      jenkinsTunnel: "${JENKINS_JNLP_SERVICE_HOST}:${JENKINS_JNLP_SERVICE_PORT_AGENT}"
      jenkinsUrl: "http://${JENKINS_SERVICE_HOST}:${JENKINS_SERVICE_PORT}"
      namespace: "${OPENSHIFT_BUILD_NAMESPACE}"
      serverUrl: "https://${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT}"
```

Might be worth documenting this somewhere for others that need it.
