### ISSUE TITLE
Pass ENV Var to the podTemplate

### ISSUE THREAD

**Issue by cmoulliard** [openshift/jenkins#290]
Since OCP 3.6 we can pass [ENV vars](https://docs.openshift.org/latest/dev_guide/builds/build_strategies.html#jenkins-pipeline-strategy-environment) to the BuildConfig/Pipeline but I don't see within the Jenkins 2 Docker image that the maven PodTemplate used to configure the pod where the build will take place as described within a groovy pipeline script will be able to reuse such ENV vars.

Is there a trick to pass them or do we have to update this file to [support it](https://github.com/openshift/jenkins/blob/master/2/contrib/jenkins/kube-slave-common.sh#L154) ?

**Comment by bparees** [comment]
The env vars should be available to the pipeline(executing within the slave pod) w/o having to configure the env vars in the pod template explicitly...  I would expect Jenkins to ensure the env vars being provided to the pipeline execution, are provided to it regardless of where the pipeline is executing.

Have you actually seen an issue?  Can you describe in more detail what you are doing (what variable you're setting, how you're using it in your pipeline)?

Adding @gabemontero

**Comment by cmoulliard** [comment]
> Can you describe in more detail

Here is the scenario that we are following.

- Every new project created within an openshift namespace will get a Jenkins Server using the jenkins ephemeral or persistent template available in Openshift
- A Buildconfig object containing a JenkinsPipelineStrategy will be created using this [template](https://github.com/cmoulliard/launchpad-missioncontrol/blob/master/services/openshift-service-impl/src/main/resources/pipeline-template.yml#L58) where the git repo corresponds to by example this project [created](https://github.com/cmoulliard/zz1/blob/master/Jenkinsfile)
- When a build is triggered (= pipeline build), jenkins will use this [slave image](https://github.com/openshiftio/launchpad-jenkins-slave-dockerfile/blob/master/Dockerfile) to create the maven jnlp slave pod where the build will take place. This pod is created using the kubernetes jenkins plugin based on the podTemplate defined [here](https://github.com/openshift/jenkins/blob/master/2/contrib/jenkins/kube-slave-common.sh#L73)

As you can see the PodTemplate defined within the script kube-slave-common.sh contains an <envVars> section that we would like to configure to pass a Build env var or param (e.g. MAVEN_MIRROR_URL)

```
<envVars>
      <org.csanchez.jenkins.plugins.kubernetes.PodEnvVar>
        <key>MAVEN_MIRROR_URL</key>
        <value>${MAVEN_MIRROR_URL}</value>
      </org.csanchez.jenkins.plugins.kubernetes.PodEnvVar>
</envVars>
```

**Comment by cmoulliard** [comment]
The only that I have been able to find for the moment to resolve this problem is to : 

1) Change the DeploymentConfig file created from the Jenkins Template to pass the MAVEN_MIRROR_URL env var

```
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: jenkins
  namespace: zz1
  labels:
    template: jenkins-persistent-template
spec:
  strategy:
    type: Recreate
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - jenkins
        from:
          kind: ImageStreamTag
          namespace: openshift
          name: 'jenkins:latest'
    - type: ConfigChange
  replicas: 1
  test: false
  selector:
    name: jenkins
  template:
    metadata:
      labels:
        name: jenkins
    spec:
      volumes:
        - name: jenkins-data
          persistentVolumeClaim:
            claimName: jenkins
      containers:
        - name: jenkins
          image: 'openshift/jenkins-2-centos7:latest'
          env:
            - name: OPENSHIFT_ENABLE_OAUTH
              value: 'true'
...
            - name: MAVEN_MIRROR_URL
              value: 'http://localhost:8080/nexus'
```
2) Update the PodTemplate `launch-maven` to pass an additional ENV var to be used by Kubernetes Jenkins Plugin when it will create ou pod responsible to do the build

<img width="1515" alt="screenshot 2017-05-08 15 55 19" src="https://cloud.githubusercontent.com/assets/463790/25807355/d7cd5712-3406-11e7-82b4-eeebb23ff529.png">

**Comment by gabemontero** [comment]
I've confirmed things are woking as we would hope an appropriate 3.6 version of origin and the latest openshift/jenkins-2-centos7 image (though any openshift jenkins image with v0.1.11 of the sync plugin should suffice) for adding env vars to pipeline build strategy builds, where the env vars will be propagated to any jenkins slaves referenced by the jenkinsfile. 

Here is a simple build config:

```
apiVersion: v1
kind: Template
labels:
  template: application-template-sample-pipeline
metadata:
  annotations:
    iconClass: icon-jenkins
    tags: instant-app,jenkins
  name: jenkins-pipeline-example
parameters:
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      name: sample-pipeline-withenvs
    name: sample-pipeline-withenvs
  spec:
    strategy:
      jenkinsPipelineStrategy:
        env:
          - name: FOO1
            value: BAR1
        jenkinsfile: |-
          node("maven") {
            echo "FOO1 is ${env.FOO1}"
            echo "FOO2 is ${env.FOO2}"
          }
      type: JenkinsPipeline
```

And here is the job output (which is what is expected):

```
In progressConsole Output

OpenShift Build myproject/sample-pipeline-withenvs-1
[Pipeline] node
Still waiting to schedule task
maven-16947a123fe5 is offline
Running on maven-16947a123fe5 in /tmp/workspace/myproject-sample-pipeline-withenvs
[Pipeline] {
[Pipeline] echo
FOO1 is BAR1
[Pipeline] echo
FOO2 is null
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
```

Now, I am not sure I entirely understand the scenario description @cmoulliard outlined.  In particular,

1) when describing the <envVars> sample that could go in the k8s plugin's PodTemplate, did you mean that would be a *default* setting for `MAVEN_MIRROR_URL`, and that you wished to then override this value via the specific Jenkinsfiles / BuildConfig ?

2) Or were you proposing that as a solution in lieu of using the env vars now available for openshift pipeline strategy builds?

If 2), then hopefully you can just mimic the example I pasted above.

If 1), then I am not sure what would take precedence.  I attempted to try it out, but am currently blocked by https://github.com/openshift/jenkins-sync-plugin/issues/132
