### ISSUE TITLE
The `oc` cli fails to apply HorizontalPodAutoscalers

### ISSUE THREAD

**Issue by tavogel** [openshift/jenkins#325]
For the past week we've been experiencing issues when applying a HorizontalPodAutoscaler via YAML to the cluster, but only on our newly built Jenkins servers:
```
error: autoscaling.HorizontalPodAutoscaler is not suitable for converting to ""
```

This has been hard to tackle, because we are reapplying the same YAML to the cluster for every deployment in our CI pipelines. The only workaround has been to comment out the YAML and instead use `oc autoscale` in our Jenkinsfile (which also requires we run `oc delete hpa` first).

In fact, as a workaround for deleting the HPA we tried the `-o yaml | oc apply -f -` trick:
```
oc autoscale dc/<my-deployment> --min 1 --max 5 --cpu-percent=80 --dry-run -o yaml | oc apply -f -
```
This also fails with the same "not suitable for converting" error as applying handwritten YAML.

I noticed that the `oc` command line has been updated to v3.6 around when this issue started to occur: https://github.com/openshift/jenkins/commit/c3bc69a0945e878644e006ca9b74c1231070a45d

Locally using `brew install openshift-cli` (oc v1.5.1) I can apply this YAML no problem. There appears to be a validation issue with the 3.6 client. We've also tried different HPA formats, e.g. autoscaling/v1, extensions/v1beta1, etc. Checking the 3.6 docs, it should support all of these.

We've also confirmed we are using the same formatting as in the latest origin docs:
```
  - apiVersion: extensions/v1beta1
    kind: HorizontalPodAutoscaler
    metadata:
      name: <my-app>
    spec:
      scaleRef:
        kind: DeploymentConfig
        name: <my-app>
        apiVersion: v1
        subresource: scale
      minReplicas: 1
      maxReplicas: 5
      cpuUtilization:
        targetPercentage: 80
```
