### ISSUE TITLE
Failure building slaves on top of OpenShift language runtime images

### ISSUE THREAD

**Issue by eamq** [openshift/jenkins#376]
Hello!

#363 introduced a change that is breaking our process for building new Jenkins slave images, as `/var/lib/origin` does not exist in the upstream Centos images used by OpenShift language runtime images (such as `openshift/python:3.5`).

Given the following OpenShift build configuration:

```
apiVersion: v1
kind: BuildConfig
metadata:
  name: jenkins-slave-python-3.5
spec:
  triggers:
    - type: ImageChange
      imageChange:
        from:
          kind: ImageStreamTag
          namespace: openshift
          name: 'python:3.5'
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift/jenkins'
    contextDir: slave-base
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'python:3.5'
      env:
        - name: http_proxy
          value: <internal proxy>
  output:
    to:
      kind: ImageStreamTag
      name: 'jenkins-slave-python:3.5'
```

...we are getting the following error while building this image:

`chmod: cannot access ‘/var/lib/origin’: No such file or directory`

While we have a workaround (specify `source.git.ref: <SHA of prior commit>`), we would love a solution that allows us to continue building new Jenkins slave base images from master in `openshift/jenkins`, while leveraging the upstream OpenShift base images instead of `openshift/origin`.

Thanks!
